model_backend: openai
model_name: gpt-5.5-2026-04-23 # the API model name
embedding_model: codefuse-ai/F2LLM-v2-1.7B
prompt_mode: title  # one of title, description, implicit, explicit
demonstration_mode: dynamic  # one of dynamic, static, None
demonstration_size: 0
embedding_mode: sparse  #one of sparse, dense, fusion, None
retrieval_mode : similarity  #one of similarity, diversity, mmr, random, None
thinking_mode: True  # or False
data_path: ./data
results_path: results/
template_path: ./templates
max_tokens: 16  # really?!